server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://dpg-cspb3j1u0jms73bi28d0-a.oregon-postgres.render.com:5432/dbrrhh
    username: dbrrhh_user
    password: BCoQXLoCqZKevns4YXGYN4REenHjKnUP

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC
    hibernate:
      ddl-auto: update
    show-sql: true

security:
  jwt:
    private:
      key: ${PRIVATE-KEY}
    user:
      generator: ${USER-GENERATOR}
